---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jlrenodi/public_html/
    - export SOURCEPATH=/home/jlrenodi/repositories/jlrenodin.software-Source/

    - /bin/rm -Rf ${DEPLOYPATH}_backup
    - /bin/cp -R ${SOURCEPATH} ${DEPLOYPATH}_backup
    # copy files to public_html to display on live site
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${SOURCEPATH}/ ${DEPLOYPATH} --delete-after

#test changes