---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jlrenodi/
    - export SOURCEPATH=/home/jlrenodi/repositories/jlrenodin.software-Source/

    - /bin/rm -Rf ${DEPLOYPATH}/public_html/_backup
    - /bin/cp -R ${SOURCEPATH} ${DEPLOYPATH}/public_html/_backup
    # copy files to public_html to display on live site
    - /bin/cp -R . ${DEPLOYPATH}/public_html